# 01 - Data Cleaning & Exploratory Data Analysis
Banking Customer Analytics Project

This notebook loads the raw synthetic banking dataset, walks through the full cleaning pipeline (missing values, duplicates, formatting, dtypes, outliers, validation), and explores the cleaned data across demographics, geography, balances, credit scores, and product ownership.

In [1]:
import sys
sys.path.append('..')

import pandas as pd
import matplotlib.pyplot as plt

from src.data_cleaning import run_cleaning_pipeline
from src import visualization as viz

pd.set_option('display.max_columns', None)

## Load raw data and inspect quality issues

In [2]:
raw_df = pd.read_csv('../data/raw/bank_customers_raw.csv')
print(raw_df.shape)
raw_df.head()

(10120, 14)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2565,15602564,Tanaka,543.0,France,female,83,3,120469.36,2,1,1,142458.53,0
1,3440,15603439,Petrov,843.0,Germany,Male,46,9,159577.32,3,1,0,134922.99,0
2,8763,15608762,Nguyen,668.0,France,Male,59,6,62206.22,1,0,0,32283.93,1
3,3736,15603735,Dubois,659.0,Spain,Male,56,6,0.0,1,1,1,120772.59,0
4,5489,15605488,Schmidt,638.0,France,Male,63,8,0.0,1,1,1,157772.43,0

In [3]:
raw_df.isna().sum()

RowNumber            0
CustomerId           0
Surname              0
CreditScore        120
Geography           50
Gender               0
Age                  0
Tenure               0
Balance            203
NumOfProducts        0
HasCrCard            0
IsActiveMember       0
EstimatedSalary     80
Exited               0
dtype: int64

In [4]:
raw_df.duplicated().sum()

np.int64(118)

## Run the full cleaning pipeline
See `src/data_cleaning.py` for the implementation of every step.

In [5]:
clean_df, report = run_cleaning_pipeline(
    raw_path='../data/raw/bank_customers_raw.csv',
    output_path='../data/processed/bank_customers_clean.csv'
)
print(report.summary())

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Loading raw data from ../data/raw/bank_customers_raw.csv

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Loaded 10120 rows, 14 columns

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Standardizing text fields (Geography, Gender, Surname)

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Fixing data types

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Handling missing values

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Filled 120 missing 'CreditScore' values with median=648.00

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Filled 203 missing 'Balance' values with median=62377.67

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Filled 80 missing 'EstimatedSalary' values with median=99564.20

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Filled missing 'Geography' values with mode='France'

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Removing duplicate records

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Removed 120 duplicate rows

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Handling outliers and impossible values

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Outlier fixes applied: {'Age_out_of_range': 15, 'CreditScore_out_of_range': 10, 'Balance_negative': 0, 'EstimatedSalary_negative': 0}

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Validating final data quality

2026-07-04 11:23:12 | INFO     | src.data_cleaning | All validation checks passed.

2026-07-04 11:23:12 | INFO     | src.data_cleaning | Saved cleaned dataset to ../data/processed/bank_customers_clean.csv

2026-07-04 11:23:12 | INFO     | src.data_cleaning |
=== DATA CLEANING REPORT ===
Initial rows: 10,120
Final rows:   10,000
Duplicates removed: 120
Missing values (before): {'RowNumber': 0, 'CustomerId': 0, 'Surname': 0, 'CreditScore': 120, 'Geography': 50, 'Gender': 0, 'Age': 0, 'Tenure': 0, 'Balance': 203, 'NumOfProducts': 0, 'HasCrCard': 0, 'IsActiveMember': 0, 'EstimatedSalary': 80, 'Exited': 0}
Missing values (after):  {'RowNumber': 0, 'CustomerId': 0, 'Surname': 0, 'CreditScore': 0, 'Geography': 0, 'Gender': 0, 'Age': 0, 'Tenure': 0, 'Balance': 0, 'NumOfProducts': 0, 'HasCrCard': 0, 'IsActiveMember': 0, 'EstimatedSalary': 0, 'Exited': 0}
Outliers fixed: {'Age_out_of_range': 15, 'CreditScore_out_of_range': 10, 'Balance_negative': 0, 'EstimatedSalary_negative': 0}
Validation errors remaining: 0

=== DATA CLEANING REPORT ===
Initial rows: 10,120
Final rows:   10,000
Duplicates removed: 120
Missing values (before): {'RowNumber': 0, 'CustomerId': 0, 'Surname': 0, 'CreditScore': 120, 'Geography': 50, 'Gender': 0, 'Age': 0, 'Tenure': 0, 'Balance': 203, 'NumOfProducts': 0, 'HasCrCard': 0, 'IsActiveMember': 0, 'EstimatedSalary': 80, 'Exited': 0}
Missing values (after):  {'RowNumber': 0, 'CustomerId': 0, 'Surname': 0, 'CreditScore': 0, 'Geography': 0, 'Gender': 0, 'Age': 0, 'Tenure': 0, 'Balance': 0, 'NumOfProducts': 0, 'HasCrCard': 0, 'IsActiveMember': 0, 'EstimatedSalary': 0, 'Exited': 0}
Outliers fixed: {'Age_out_of_range': 15, 'CreditScore_out_of_range': 10, 'Balance_negative': 0, 'EstimatedSalary_negative': 0}
Validation errors remaining: 0

In [6]:
clean_df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15602564,Tanaka,543.0,France,Female,83,3,120469.36,2,1,1,142458.53,0
1,15603439,Petrov,843.0,Germany,Male,46,9,159577.32,3,1,0,134922.99,0
2,15608762,Nguyen,668.0,France,Male,59,6,62206.22,1,0,0,32283.93,1
3,15603735,Dubois,659.0,Spain,Male,56,6,0.00,1,1,1,120772.59,0
4,15605488,Schmidt,638.0,France,Male,63,8,0.00,1,1,1,157772.43,0

## Exploratory Data Analysis
### Demographics: Gender & Age

In [7]:
clean_df['Gender'].value_counts(normalize=True).round(3) * 100

Gender
Male      50.2
Female    49.8
Name: proportion, dtype: float64

In [8]:
clean_df['Age'].describe()

count    10000.000000
mean        55.676000
std         12.553533
min         25.000000
25%         47.000000
50%         54.000000
75%         63.000000
max        100.000000
Name: Age, dtype: float64

In [9]:
fig, ax = plt.subplots(figsize=(7,4))
ax.hist(clean_df['Age'], bins=30, color='#0f4c81', edgecolor='white')
ax.set_title('Age Distribution')
ax.set_xlabel('Age')
plt.show()

### Geography

In [10]:
clean_df['Geography'].value_counts()

Geography
France     4987
Spain      2555
Germany    2458
Name: count, dtype: int64

### Account Balance

In [11]:
clean_df['Balance'].describe()

count     10000.000000
mean      62436.351356
std       58130.391536
min           0.000000
25%           0.000000
50%       62377.670000
75%      108807.072500
max      260000.000000
Name: Balance, dtype: float64

In [12]:
(clean_df['Balance'] == 0).sum(), (clean_df['Balance'] == 0).mean().round(3)

(np.int64(3596), np.float64(0.36))

### Credit Score

In [13]:
clean_df['CreditScore'].describe()

count    10000.000000
mean       648.630900
std         94.883807
min        300.000000
25%        586.000000
50%        648.000000
75%        713.000000
max        850.000000
Name: CreditScore, dtype: float64

### Estimated Salary

In [14]:
clean_df['EstimatedSalary'].describe()

count     10000.000000
mean      99414.717272
std       57551.808037
min          18.220000
25%       49869.190000
50%       99564.200000
75%      149146.832500
max      199989.740000
Name: EstimatedSalary, dtype: float64

### Products Owned

In [15]:
clean_df['NumOfProducts'].value_counts().sort_index()

NumOfProducts
1    5093
2    3986
3     720
4     201
Name: count, dtype: Int64

### Active vs Inactive Customers

In [16]:
clean_df['IsActiveMember'].value_counts(normalize=True).round(3) * 100

IsActiveMember
1    52.6
0    47.4
Name: proportion, dtype: Float64

## Generate all static report charts (saved to ../images/)

In [17]:
import os
os.chdir('..')
viz.generate_all_static_charts(clean_df)
os.chdir('notebooks')

2026-07-04 11:23:13 | INFO     | src.visualization | Saved images/gender_distribution.png

2026-07-04 11:23:13 | INFO     | src.visualization | Saved images/age_distribution.png

2026-07-04 11:23:13 | INFO     | src.visualization | Saved images/geography_distribution.png

2026-07-04 11:23:13 | INFO     | src.visualization | Saved images/balance_distribution.png

2026-07-04 11:23:13 | INFO     | src.visualization | Saved images/credit_score_distribution.png

2026-07-04 11:23:14 | INFO     | src.visualization | Saved images/churn_by_geography.png

2026-07-04 11:23:14 | INFO     | src.visualization | Saved images/active_vs_inactive.png

2026-07-04 11:23:14 | INFO     | src.visualization | Saved images/products_owned.png

2026-07-04 11:23:14 | INFO     | src.visualization | All static charts generated in images

## Key EDA Takeaways
- The dataset spans three European markets (France, Germany, Spain) with France representing roughly half the customer base.
- Age is right-skewed, with most customers between 30-50 and a smaller senior population (60+) that, as later analysis shows, churns disproportionately.
- Around a third of customers hold a zero balance, an important segment for targeted engagement.
- Credit scores are approximately normally distributed around the mid-600s, typical of a mainstream retail banking population.
- Most customers hold 1-2 products; very few hold 3-4, representing a cross-sell growth opportunity explored in the segmentation notebook.